name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every day at midnight UTC
  workflow_dispatch:     # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: ${{ github.repository_owner }}
          show_icons: true
          include_all_commits: true
          count_private: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
